apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: k8s-test
    role: slave
    tier: backend
    type: db
spec:
  selector:
    matchLabels:
      app: k8s-test
      role: slave
      tier: backend
      type: db
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-test
        role: slave
        tier: backend
        type: db
    spec:
      containers:
        - name: slave
          image: fabry/gb-redisslave:v3 # gcr.io/google_samples/gb-redisslave:v3
          volumeMounts:
                - mountPath: /data
                  name: datadir
          resources:
            limits:
              memory: 64M
              cpu: ".1"
          env:
          - name: GET_HOSTS_FROM
            value: dns
            # Using `GET_HOSTS_FROM=dns` requires your cluster to
            # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
            # service launched automatically. However, if the cluster you are using
            # does not have a built-in DNS service, you can instead
            # access an environment variable to find the master
            # service's host. To do so, comment out the 'value: dns' line above, and
            # uncomment the line below:
            # value: env
          ports:
          - containerPort: 6379
      volumes:
        - name: datadir
          emptyDir: {}