apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  labels:
    app: k8s-test
    tier: backend
    type: api
spec:
  replicas: 2
  revisionHistoryLimit: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: k8s-test
      tier: backend
      type: api
  template:
    metadata:
      labels:
        app: k8s-test
        tier: backend
        type: api
    spec:
      containers:
        - name: api-gateway-service
          image: fabry/k8s-test-api-gateway-service:1.1.4
          resources:
            limits:
              memory: 256M
              cpu: ".3"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 300
            timeoutSeconds: 5
            periodSeconds: 60
            failureThreshold: 1
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: k8s-test-configs
