apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-master-pv-volume
  labels:
    app: k8s-test
    role: master
    tier: backend
    type: db    
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"