apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: k8s-test
    tier: frontend
    type: app
spec:
  type: ClusterIP
  selector:
    app: k8s-test
    tier: frontend
    type: app
  ports:
    - port: 3000
      targetPort: 3000
