apiVersion: v1
kind: Service
metadata:
   name: data-service
   labels:
        app: k8s-test
        tier: backend
        type: data
spec:
  type: NodePort
  selector: 
    app: k8s-test
    tier: backend
    type: data
  ports:
    - port: 9090
      targetPort: 8080
      nodePort: 31000
    