app:
  version: 1.0.0
  environment: none
  pod-id: ${MY_POD_NAME:unknown}
  pod-namespace: ${MY_POD_NAMESPACE:unknown}
  pod-ip: ${MY_POD_ip:unknown}
  auth-endpoint: ${USER_SERVICE:http://user-service:8080/api/users/from-token/}
  redis-master-host: ${USER_SERVICE:redis-master}
  redis-master-port: ${USER_SERVICE:6379}
  cache:
    max-values: 1000
    ttl-minutes: 30
