app:
  version: 1.0.0
  environment: none
  pod-id: ${MY_POD_NAME:unknown}
  pod-namespace: ${MY_POD_NAMESPACE:unknown}
  pod-ip: ${MY_POD_ip:unknown}
  auth-endpoint: ${USER_SERVICE:http://user-service:8080/api/users/from-token/}
  redis-master-host: ${REDIS_HOST:redis-master}
  redis-master-port: ${REDIS_PORT:6379}
  cache:
    default-ttl-minutes: 10
    cacheExpirations:
      usersTokensCache: 180

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info, caches
