api:
  gateway:
    version: 1.0.0
    environment: none
    pod-id: ${MY_POD_NAME:unknown}
    pod-namespace: ${MY_POD_NAMESPACE:unknown}
    pod-ip: ${MY_POD_ip:unknown}
    cache:
      max-values: 1000
      ttl-minutes: 30
    services:
      todo: ${TODO_SERVICE:todo-service:8080}
      user: ${USER_SERVICE:user-service:8080}
    endpoints:
      - location: http://${api.gateway.services.todo}
        method: GET
        path: '[/]*api/todos.*'
        name: todo-service
      - location: http://${api.gateway.services.user}
        path: '[/]*api/users.*'
        name: user-service
      - location: http://${api.gateway.services.user}
        path: '[/]*api/authenticate.*'
        name: user-service
