api:
  gateway:
    environment: none
    pod-id: local
    pod-namespace: local
    pod-ip: local
    cache:
      max-values: 1000
      ttl-minutes: 30
    services:
      todo: "localhost:9090"
      user: "localhost:9091"